import type { Drop, Product } from "./types";

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const MOCK_DROPS: Drop[] = [
  {
    id: "drop-01",
    slug: "radar-toquio",
    name: "Radar Tóquio",
    description:
      "Primeiro drop da NYX. Peças garimpadas em feiras independentes de Tóquio e Osaka. Edições numeradas, sem reposição.",
    releaseDate: now - 14 * day,
    status: "active",
    heroImage: "https://picsum.photos/seed/nyx-drop-01/1600/900",
    createdAt: now - 30 * day,
    updatedAt: now - 14 * day,
  },
  {
    id: "drop-02",
    slug: "silencio-urbano",
    name: "Silêncio Urbano",
    description:
      "Segundo drop. Paleta deslavada, cortes oversized, inspiração em workwear japonês dos anos 90.",
    releaseDate: now + 21 * day,
    status: "upcoming",
    heroImage: "https://picsum.photos/seed/nyx-drop-02/1600/900",
    createdAt: now - 7 * day,
    updatedAt: now - 1 * day,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p-001",
    slug: "camiseta-noir-oversized",
    name: "Camiseta Noir Oversized",
    description:
      "Algodão japonês pesado 280g/m². Corte oversized, gola reforçada, acabamento lavado. Peça numerada.",
    category: "camisetas",
    pricePix: 289,
    priceCard: 320,
    images: [
      "https://picsum.photos/seed/nyx-p001-a/800/1000",
      "https://picsum.photos/seed/nyx-p001-b/800/1000",
      "https://picsum.photos/seed/nyx-p001-c/800/1000",
    ],
    sizes: [
      { size: "P", quantity: 2 },
      { size: "M", quantity: 3 },
      { size: "G", quantity: 1 },
      { size: "GG", quantity: 0 },
    ],
    dropId: "drop-01",
    isLimited: true,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 2 * day,
  },
  {
    id: "p-002",
    slug: "moletom-shibuya-cru",
    name: "Moletom Shibuya Cru",
    description:
      "Moletom flanelado 420g/m² em tom cru. Bordado tonal do logotipo NYX no peito. Produção limitada a 12 peças.",
    category: "moletons",
    pricePix: 549,
    priceCard: 610,
    images: [
      "https://picsum.photos/seed/nyx-p002-a/800/1000",
      "https://picsum.photos/seed/nyx-p002-b/800/1000",
    ],
    sizes: [
      { size: "P", quantity: 0 },
      { size: "M", quantity: 2 },
      { size: "G", quantity: 1 },
      { size: "GG", quantity: 0 },
    ],
    dropId: "drop-01",
    isLimited: true,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: "p-003",
    slug: "calca-cargo-ashigaru",
    name: "Calça Cargo Ashigaru",
    description:
      "Cargo em sarja pesada com cós ajustável, seis bolsos utilitários e barra reforçada. Tingimento manual.",
    category: "calcas",
    pricePix: 629,
    priceCard: 699,
    images: [
      "https://picsum.photos/seed/nyx-p003-a/800/1000",
      "https://picsum.photos/seed/nyx-p003-b/800/1000",
    ],
    sizes: [
      { size: "P", quantity: 1 },
      { size: "M", quantity: 2 },
      { size: "G", quantity: 2 },
      { size: "GG", quantity: 1 },
    ],
    dropId: "drop-01",
    isLimited: false,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 5 * day,
  },
  {
    id: "p-004",
    slug: "jaqueta-coach-kageboshi",
    name: "Jaqueta Coach Kageboshi",
    description:
      "Coach jacket em nylon hidrofugado com forro em algodão. Silhueta reta, punhos elásticos, serigrafia nas costas.",
    category: "jaquetas",
    pricePix: 879,
    priceCard: 979,
    images: [
      "https://picsum.photos/seed/nyx-p004-a/800/1000",
      "https://picsum.photos/seed/nyx-p004-b/800/1000",
      "https://picsum.photos/seed/nyx-p004-c/800/1000",
    ],
    sizes: [
      { size: "P", quantity: 1 },
      { size: "M", quantity: 1 },
      { size: "G", quantity: 0 },
      { size: "GG", quantity: 0 },
    ],
    dropId: "drop-01",
    isLimited: true,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 3 * day,
  },
  {
    id: "p-005",
    slug: "boneh-neve-cinza",
    name: "Gorro Neve Cinza",
    description: "Gorro em tricô de lã merino cinza. Etiqueta de couro na lateral, encaixe justo.",
    category: "acessorios",
    pricePix: 189,
    priceCard: 210,
    images: [
      "https://picsum.photos/seed/nyx-p005-a/800/1000",
      "https://picsum.photos/seed/nyx-p005-b/800/1000",
    ],
    sizes: [{ size: "UNICO", quantity: 6 }],
    dropId: "drop-01",
    isLimited: false,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 7 * day,
  },
  {
    id: "p-006",
    slug: "camiseta-manifesto-off",
    name: "Camiseta Manifesto Off",
    description:
      "Peça base em algodão peruano 220g/m². Estampa do manifesto NYX em serigrafia interna. Off-white quente.",
    category: "camisetas",
    pricePix: 249,
    priceCard: 279,
    images: [
      "https://picsum.photos/seed/nyx-p006-a/800/1000",
      "https://picsum.photos/seed/nyx-p006-b/800/1000",
    ],
    sizes: [
      { size: "P", quantity: 0 },
      { size: "M", quantity: 0 },
      { size: "G", quantity: 0 },
      { size: "GG", quantity: 0 },
    ],
    dropId: "drop-01",
    isLimited: true,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 1 * day,
  },
  {
    id: "p-007",
    slug: "moletom-sem-costura-fumaca",
    name: "Moletom Sem Costura Fumaça",
    description:
      "Construção tubular sem costura lateral, 380g/m². Tingimento sobreposto que varia peça a peça.",
    category: "moletons",
    pricePix: 579,
    priceCard: 645,
    images: [
      "https://picsum.photos/seed/nyx-p007-a/800/1000",
      "https://picsum.photos/seed/nyx-p007-b/800/1000",
    ],
    sizes: [
      { size: "P", quantity: 2 },
      { size: "M", quantity: 2 },
      { size: "G", quantity: 2 },
      { size: "GG", quantity: 1 },
    ],
    dropId: "drop-01",
    isLimited: true,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 4 * day,
  },
  {
    id: "p-008",
    slug: "bolsa-tiracolo-ronin",
    name: "Bolsa Tiracolo Ronin",
    description:
      "Bolsa utilitária em cordura preta com alça regulável, bolso interno com zíper e etiqueta serigrafada.",
    category: "acessorios",
    pricePix: 349,
    priceCard: 389,
    images: [
      "https://picsum.photos/seed/nyx-p008-a/800/1000",
      "https://picsum.photos/seed/nyx-p008-b/800/1000",
    ],
    sizes: [{ size: "UNICO", quantity: 3 }],
    dropId: "drop-01",
    isLimited: false,
    colors: [],
    status: "published",
    createdAt: now - 14 * day,
    updatedAt: now - 6 * day,
  },
];
